In [4]:
import glob
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from PIL import Image


import os
import io

In [5]:
print(os.getcwd())
current = os.getcwd()
data_folder = current + "/data"
chess_types_folders = glob.glob(data_folder + "/*")
# print(chess_types_folders)
pieces_info = []
for chess_types in chess_types_folders:
    pieces = glob.glob(f'{chess_types}/*')
    # print(pieces)
    type = chess_types.split("/")[-1]
    for piece in pieces:
        p = {"image_path": piece, "label": type}
        pieces_info.append(p)
chess_df = pd.DataFrame(pieces_info)


/Users/khanhchile/Downloads/School/CSCI 5525/5525Chess


In [6]:
chess_df.head()

image_path   label
0  /Users/khanhchile/Downloads/School/CSCI 5525/5...  Bishop
1  /Users/khanhchile/Downloads/School/CSCI 5525/5...  Bishop
2  /Users/khanhchile/Downloads/School/CSCI 5525/5...  Bishop
3  /Users/khanhchile/Downloads/School/CSCI 5525/5...  Bishop
4  /Users/khanhchile/Downloads/School/CSCI 5525/5...  Bishop

In [7]:
# Directory to save preprocessed images 64x64
output_dir = "normalized_images_64"
os.makedirs(output_dir, exist_ok=True)

# Normalize and save images
labels = sorted(chess_df['label'].unique())
for label in labels:
    label_dir = os.path.join(output_dir, str(label))  # Create a subdirectory for each label
    os.makedirs(label_dir, exist_ok=True)
    
    for im_pth in chess_df[chess_df['label'] == label]['image_path']:
        # Open and preprocess the image
        image = Image.open(im_pth).convert('L').resize((64, 64))
        image_array = np.array(image) / 255.0  # Normalize to [0, 1]
        print(image_array)
        np.save(os.path.join(label_dir, f"normalized_{os.path.basename(im_pth)}.npy"), image_array)
        # Option

[[0.72156863 0.73333333 0.74509804 ... 0.63529412 0.62745098 0.62352941]
 [0.36862745 0.37647059 0.39215686 ... 0.68235294 0.67843137 0.67843137]
 [0.36862745 0.37647059 0.38039216 ... 0.69803922 0.69803922 0.69411765]
 ...
 [0.30196078 0.29803922 0.29803922 ... 0.39607843 0.38823529 0.39607843]
 [0.29019608 0.29411765 0.29411765 ... 0.39215686 0.38431373 0.40392157]
 [0.29411765 0.29803922 0.30588235 ... 0.38039216 0.38431373 0.39607843]]
[[0.98823529 1.         1.         ... 1.         1.         0.98823529]
 [0.99607843 0.99215686 1.         ... 1.         0.99215686 0.99607843]
 [1.         0.99607843 0.99215686 ... 0.99215686 0.99607843 1.        ]
 ...
 [0.99215686 1.         1.         ... 0.98823529 0.99215686 0.99215686]
 [1.         1.         1.         ... 0.83529412 0.9254902  1.        ]
 [1.         1.         1.         ... 0.90196078 0.98823529 1.        ]]
[[0.17647059 0.53333333 0.74901961 ... 0.83137255 0.82745098 0.82352941]
 [0.23921569 0.65490196 0.74901961 ... 